### ISSUE TITLE
Wrong update in the neural network

### ISSUE THREAD

**Issue by jcyuan78** [matthewrdev/Neural-Network#1]
In the NeuralNet::Update() method, you assigned the outputs to the inputs then repeat the calculation for each layer.
However, you forget to clear the obsoleted data in the outputs. So the new result of the next layer will be appended to the outputs. It causes that the new result does not go to the next calculation.
I tried to fix this issue. However, I found that the fixed code‘s iteration speed becomes slower than the original one. I don't know the reason. Do you have any comments?

**Comment by matthewrdev** [comment]
Hi @jcyuan78, thanks for filing an issue.

As this project was from my uni days (10 years ago), it is no longer maintained and won't receive any bug fixes or updates.
